name: Tabroom Indexcards API Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
    CI: true
    HUSKY: 0
    REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
    REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
    SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    CODE_PATH: "/home/runner/work/indexcards/indexcards"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set Docker Tag by commit
      id: get_version
      run: echo COMMIT_VERSION=$(echo $GITHUB_SHA) >> $GITHUB_ENV

    - name: Publish Indexcards image to Registry
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: nsda/indexcards
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        registry: registry.speechanddebate.org
        tags: "${{ env.COMMIT_VERSION }}"

    - name: Publish cron image to Registry
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: nsda/indexcards/cron
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        registry: registry.speechanddebate.org
        tags: "${{ env.COMMIT_VERSION }}"
        dockerfile: cron.Dockerfile

    - name: If image was published change icon
      if: success()
      run: echo "SLACK_ICON=:white_check_mark:" >> $GITHUB_ENV

    - name: Send slack notification
      uses: speechanddebate/action-slack-notify@master
